services:
  api:
    build: .
    ports:
      - "3001:3001"
    volumes:
      # Монтируем локальную папку в контейнер
      - ./apps/api:/usr/src/app/apps/api
      # Важно: исключаем node_modules из монтирования, 
      # чтобы локальные папки не перетирали зависимости контейнера
      - /usr/src/app/apps/api/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - PRISMA_CONFIG_PATH=/usr/src/app/apps/api/src/prisma/prisma.config.ts
    # Используем команду для разработки (обычно это nest start --watch)
    command: npm run start:dev

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: