auth:
  username: app
  password: app
  database: app

primary:
  persistence:
    enabled: true
    size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi