import type { Metadata } from "next";
import localFont from "next/font/local";
import "../shared/styles/globals.css";

import { Separator } from "@/components/ui/separator";
import { Providers } from "@/providers/providers";
import { Header } from "../widgets/header";

const geistSans = localFont({
  src: "../shared/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../shared/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable}`}
      >
        <Providers>
          <Header />
          <Separator />

          <div className="flex flex-1">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
