export const RABBITMQ_MODULE_OPTIONS = 'RABBITMQ_MODULE_OPTIONS';
export const RABBITMQ_CONFIG = 'RABBITMQ_CONFIG';
export const RABBITMQ_CONNECTION = 'RABBITMQ_CONNECTION';
export const RABBITMQ_PRODUCER = 'RABBITMQ_PRODUCER';
export const RABBITMQ_CONSUMER = 'RABBITMQ_CONSUMER';
export const RABBITMQ_QUEUE_MANAGER = 'RABBITMQ_QUEUE_MANAGER';
export const RABBITMQ_SERIALIZER = 'RABBITMQ_SERIALIZER';
export const RABBITMQ_ERROR_HANDLER = 'RABBITMQ_ERROR_HANDLER';
export const RABBITMQ_HEALTH = 'RABBITMQ_HEALTH';
export const RABBITMQ_LOGGER = 'RABBITMQ_LOGGER';
export const RABBITMQ_MONITORING = 'RABBITMQ_MONITORING';

export const RABBITMQ_EMAIL_PRODUCER = 'RABBITMQ_EMAIL_PRODUCER';
export const RABBITMQ_ORDER_PRODUCER = 'RABBITMQ_ORDER_PRODUCER';
export const RABBITMQ_NOTIFICATION_PRODUCER = 'RABBITMQ_NOTIFICATION_PRODUCER';

export const RABBITMQ_EMAIL_CONSUMER = 'RABBITMQ_EMAIL_CONSUMER';
export const RABBITMQ_ORDER_CONSUMER = 'RABBITMQ_ORDER_CONSUMER';
export const RABBITMQ_NOTIFICATION_CONSUMER = 'RABBITMQ_NOTIFICATION_CONSUMER';

export const RABBITMQ_QUEUE_DEFINITIONS = 'RABBITMQ_QUEUE_DEFINITIONS';
