name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. Применяем миграции к продакшн-базе (Neon)
      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # В проде используем deploy, а не dev
          npx prisma migrate deploy --schema=./src/prisma/schema.prisma
      
      # 2. Здесь был бы шаг деплоя на хостинг (например, Railway или Render)
      - name: Deploy
        run: echo "Код готов к деплою! Подключи Railway/Render к этому репозиторию."