spec:
  project: human-system-design
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/vladyslav-dmitriev/human-system-design.git
    targetRevision: main
    path: infra/helm/vendors/cert-manager
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true