apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: human-system-design
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.3.4  # Более старая версия
    chart: grafana
    helm:
      values: |
        podSecurityPolicy:
          enabled: false
        persistence:
          enabled: false
        service:
          type: ClusterIP
        rbac:
          pspEnabled: false
        adminPassword: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRun=true
  ignoreDifferences:
  - group: policy
    kind: PodSecurityPolicy
    jsonPointers:
    - /spec