apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: human-system-design
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/vladyslav-dmitriev/human-system-design.git
    targetRevision: main
    path: infra/helm/vendors/prometheus
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true